[package]
name = "tokay"
version = "0.6.0"
description = "Tokay is a programming language designed for ad-hoc parsing."
authors = [
    "Jan Max Meyer <jmm@phorward.de>"
]
homepage = "https://tokay.dev/"
repository = "https://github.com/tokay-lang/tokay/"
license = "MIT"
edition = "2021"
categories = [
    "parsing",
    "compilers",
    "command-line-utilities",
    "development-tools"
]
keywords = [
    "awk",
    "dsl",
    "packrat",
    "parser",
    "vm"
]

[features]
default = ["static_expression_evaluation"]
static_expression_evaluation = []  # Evaluates static expressions like 1+2+3 during compile-time to reduce resulting operations

[build-dependencies]
tokay = "0.4"
glob = "0.3"

[dependencies]
charclass = "0.2"  # use crates.io-version
#charclass = { version = "0.2", path = "../charclass" }  # use local version
clap = { version = "4", features = ["derive"] }
glob = "0.3"
indexmap = "1.9"
num = "0.4"
num-bigint = "0.4"
rustyline = "9"
#tokay-macros = "0.2"  # use crates.io-version
tokay-macros = { version = "0.2", path = "macros" }  # use local version
num-parse = "0.1"  # use crates.io-version
#num-parse = { version = "0.1", path = "../num-parse" }  # use local version
